spring:
  application:
    name: edtech-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/edtech
    username: edtech
    password: edtech

  flyway:
    enabled: true
    locations: classpath:db/migration

identity:
  token:
    verification-ttl: 5m
